### ISSUE TITLE
Failed to download (rec) JOAB program

### ISSUE THREAD

**Issue by akiradeveloper** [yyoshiki41/radigo#55] opened 2020-07-27 00:14 UTC
According to https://www.nhk.or.jp/pr/keiei/otherpress/pdf/20190322.pdf, JOAB is not able to download as of 2020? wtf...

I could download something from JOAK using the docker container so I am sure my setting is right.

```
$ docker run -it -v ~/radiko/:/output yyoshiki41/radigo rec -id=JOAK -s=20200722010000
Now downloading..
|
+------------+----------+
| STATION ID |  TITLE   |
+------------+----------+
| JOAK       | ニュース |
+------------+----------+
/ Completed!
/output/20200722010000-JOAK.aac
```

**Comment by yyoshiki41** [comment] 2020-07-31 05:04
Sorry, I could not answer..
Official faq is bellow.
http://faq.radiko.jp/faq/show/289?site_domain=default

Close this issue because it was not caused by radigo.
Thanks!!

**Closed as completed by yyoshiki41** 2020-07-31 05:04 UTC
